
spring:
  application:
    name: seata-storage-provider
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #新的驱动需要在URL中添加时区设置，否则会报错
    url: jdbc:mysql://192.168.2.119:28002/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
dubbo:
  application:
    name: seata-storage-provider
  registry:
    address: nacos://192.168.2.119:11125
  protocol:
    name: dubbo
    port: 20888

mybatis-plus:
  mapper-locations: classpath*:com/k21d/springboot/storage/provider/mapper/xml/*Mapper.xml
  type-aliases-package: com.k21d.springboot.storage.provider.entity
  global-config:
    db-config:
      id-type: id_worker
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
